#!/usr/bin/env bash
set -euo pipefail

DOTFILES="$(cd "$(dirname "$0")" && pwd)"

mkdir -p "$HOME/.config/tmux"
ln -sf "$DOTFILES/tmux/tmux.conf" "$HOME/.config/tmux/tmux.conf"
ln -sf "$DOTFILES/git/gitconfig" "$HOME/.gitconfig"

# Idempotently source repo-managed shell fragments from the live rc files.
# (rc files themselves are regenerated by the base image, so we append, not symlink.)
ensure_source() {
	# $1 = rc file, $2 = fragment path
	grep -qxF "source $2" "$1" 2>/dev/null || echo "source $2" >> "$1"
}

ensure_source "$HOME/.bashrc" "$DOTFILES/bash/aliases"
ensure_source "$HOME/.bashrc" "$DOTFILES/bash/prompt"
ensure_source "$HOME/.zshrc"  "$DOTFILES/zsh/prompt.zsh"
